server {
    listen 443 ssl;
    server_name mex.app.br;

    ssl_certificate /etc/letsencrypt/live/mex.app.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mex.app.br/privkey.pem;

    # SPA admin em /admin/
    location ^~ /admin/ {
        alias /home/ubuntu/mex-admin/dist/;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
        add_header Cache-Control "no-cache";
    }
    location = /admin {
        return 301 /admin/;
    }
}